export const GET_NEW_ARTICLE_PENDING = 'GET_NEW_ARTICLE_PENDING';
export const GET_NEW_ARTICLE_SUCCESS = 'GET_NEW_ARTICLE_SUCCESS';
export const GET_NEW_ARTICLE_FAILED = 'GET_NEW_ARTICLE_FAILED';

export const GET_MOVIE_PENDING = 'GET_MOVIE_PENDING';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';
